---
.gitlab-ci.yml:
  # we've converted over to GitHub ations
  unmanaged: true
.gitignore:
  paths:
    - .rerun.json
    - .resource_types
    - .librarian
    - .kitchen
    - .tmp
    - .bundle
    - .devcontainer
    - .vscode
    - .travis.yml
    - .gitlab-ci.yml
    - bolt.log
    - bolt-debug.log
    - Puppetfile.lock
    - modules
.rubocop.yml:
  default_configs:
    AllCops:
      Exclude:
        - modules/**/*
.travis.yml:
  # we've converted over to GitHub ations
  unmanaged: true
.vscode/extensions.json:
  # we don't use vscode
  unmanaged: true
appveyor.yml:
  # we don't use Appveyor
  unmanaged: true
Gemfile:
  required:
    ':development':
      - gem: 'generate-puppetfile'
        version: '>= 1.0.0'
      - gem: 'onceover'
        version: '>= 3.0.0'
      - gem: 'puppet-blacksmith'
        version: '>= 5.0.0'
      - gem: 'puppet-lint-absolute_template_path'
        version: '>= 1.0.1'
      - gem: 'puppet-lint-alias-check'
        version: '>= 0.1.1'
      - gem: 'puppet-lint-classes_and_types_beginning_with_digits-check'
        version: '>= 0.1.2'
      - gem: 'puppet-lint-concatenated_template_files-check'
        version: '>= 0.1.1'
      - gem: 'puppet-lint-file_ensure-check'
        version: '>= 0.3.1'
      - gem: 'puppet-lint-file_source_rights-check'
        version: '>= 0.1.1'
      - gem: 'puppet-lint-leading_zero-check'
        version: '>= 0.1.1'
      - gem: 'puppet-lint-resource_reference_syntax'
        version: '>= 1.0.10'
      - gem: 'puppet-lint-trailing_comma-check'
        version: '>= 0.3.2'
      - gem: 'puppet-lint-unquoted_string-check'
        version: '>= 0.3.0'
      - gem: 'puppet-lint-version_comparison-check'
        version: '>= 0.2.1'
      - gem: 'r10k'
        version: '>= 3.3.0'
      - gem: 'yaml-lint'
        version: '>= 0.0.10'
Rakefile:
  extras:
    - "# Exclude external modules from syntax testing"
    - "PuppetSyntax.exclude_paths << 'modules/**/*'"
    - "# Include syntax testin for plans"
    - "PuppetSyntax.exclude_paths.delete('plans/**/*')"
spec/spec_helper.rb:
  mock_with: ':rspec'
